### ISSUE TITLE
Did you shutdown the API?

### ISSUE THREAD

**Issue by mkll** [chain-engineering/chain-node#29]

**Comment by ryandotsmith** [comment]
Hello @mkll,

We did in fact sunset the Free Bitcoin API. Here is the email we sent out in November:

> Dear friends of Chain,
> 
> I'm writing to let you know that the free tier of Chain's Bitcoin API service will be sunsetting on December 31, 2015.
> 
> As most of you know, over the last year Chain's focus has shifted to enabling financial institutions to issue and manage digital assets on blockchain networks. As we move into 2016, we will be folding our bitcoin capabilities into this enterprise platform. We will no longer support free projects on the bitcoin network.
> 
> Our first priority is ensuring your applications continue running uninterrupted. If you would like technical assistance to migrate your bitcoin app to another vendor's free or low-cost bitcoin API service, our CTO Ryan Smith (ryan@chain.com) is available to support you and ensure your application has a seamless transition. We have helped many projects do this already.
> 
> If your project or company is a fit for our enterprise platform and you would like to learn more, please contact Adam Ludwin (adam@chain.com).
> 
> Thank you and please feel free to reach out with any questions. We've enjoyed working with each of you and appreciate your support.
> 
> Best,
> Adam

If there is anything I can do to help, please let me know.

**Comment by fanatid** [comment]
@ryandotsmith maybe in this case, it make sense add note about this to repository and mark package on npm.js as deprecated?

**Comment by mkll** [comment]
@ryandotsmith Ok, thanks, I have never received such a email.
There is a bunch of Chain's repositories here and all they looks orphaned. Just a few words in README.MD of each of them, and the situation would become very clear.

**Comment by ryandotsmith** [comment]
@mkll @fanatid This makes sense. We'll work on making it clear in the READMEs of these projects.
